[package]
name = "ablomm_asm"
version = "1.0.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.12.0"
clap = { version = "4.5.51", features = ["derive"] }
indexmap = "2.12.0"
internment = "0.8.6"
